import type { Idea } from '@/types'

export const MOCK_IDEAS: Idea[] = [
  {
    id: '1',
    source: 'trending',
    created_by: null,
    title: 'How I saved ₹50,000 in 6 months on a ₹30k salary',
    description: 'Personal finance breakdown showing exact budget splits, zero-based budgeting, and small wins that compound. Real numbers, real story.',
    hook_preview: '"Everyone says save money. Nobody shows HOW on a low salary. Here\'s my exact breakdown..."',
    niche: 'finance',
    sub_niche: 'personal savings',
    platforms: ['instagram', 'youtube'],
    recommended_format: 'reel',
    difficulty: 'easy',
    estimated_minutes: 30,
    viral_score: 91,
    trending_reason: '4.2M views on similar content this week',
    similar_views_avg: 890000,
    is_active: true,
    expires_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    source: 'trending',
    created_by: null,
    title: '5 AI tools replacing expensive freelancers in 2025',
    description: 'Practical demo of 5 tools that automate design, writing, video editing, and customer support. Cost comparison included.',
    hook_preview: '"I paid someone ₹20,000 a month for this. Now I use these 5 free tools instead..."',
    niche: 'tech',
    sub_niche: 'AI tools',
    platforms: ['youtube', 'instagram'],
    recommended_format: 'short',
    difficulty: 'medium',
    estimated_minutes: 45,
    viral_score: 87,
    trending_reason: 'AI tools niche up 340% search volume',
    similar_views_avg: 650000,
    is_active: true,
    expires_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    source: 'trending',
    created_by: null,
    title: 'What no one tells you about starting a YouTube channel',
    description: 'The real numbers: views, revenue, time invested vs returns. Myth-busting format showing month-by-month data.',
    hook_preview: '"I made ₹0 for 8 months. Here\'s what actually changes everything in month 9..."',
    niche: 'education',
    sub_niche: 'creator economy',
    platforms: ['youtube', 'instagram'],
    recommended_format: 'long_form',
    difficulty: 'medium',
    estimated_minutes: 90,
    viral_score: 84,
    trending_reason: 'Creator economy content surging after YT update',
    similar_views_avg: 1200000,
    is_active: true,
    expires_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    source: 'trending',
    created_by: null,
    title: 'Gym workout for people who hate the gym',
    description: 'Minimal equipment, 30-min sessions, real body transformation. Anti-gym-bro energy. Relatable and achievable.',
    hook_preview: '"Been going to the gym for 2 years with zero results. Then I changed one thing..."',
    niche: 'fitness',
    sub_niche: 'beginner fitness',
    platforms: ['instagram', 'youtube', 'tiktok'],
    recommended_format: 'reel',
    difficulty: 'easy',
    estimated_minutes: 35,
    viral_score: 88,
    trending_reason: '2.1M saves on anti-bro fitness content this month',
    similar_views_avg: 750000,
    is_active: true,
    expires_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    source: 'trending',
    created_by: null,
    title: 'Morning routine that actually changed my productivity',
    description: 'A realistic 45-min morning routine with science behind each habit. No 4am wakeups, no ice baths, no hustle porn.',
    hook_preview: '"I\'m not a morning person. This routine works even if you sleep until 8am..."',
    niche: 'lifestyle',
    sub_niche: 'productivity',
    platforms: ['instagram', 'tiktok'],
    recommended_format: 'reel',
    difficulty: 'easy',
    estimated_minutes: 25,
    viral_score: 79,
    trending_reason: 'Productivity consistently top-5 saves category',
    similar_views_avg: 420000,
    is_active: true,
    expires_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    source: 'trending',
    created_by: null,
    title: 'Restaurant-quality biryani — the step everyone skips',
    description: 'Step-by-step recipe exposing the one technique that separates home cooks from restaurant quality.',
    hook_preview: '"Every biryani recipe lies to you about one step. Here\'s what they all skip..."',
    niche: 'food',
    sub_niche: 'Indian cooking',
    platforms: ['instagram', 'youtube'],
    recommended_format: 'reel',
    difficulty: 'medium',
    estimated_minutes: 40,
    viral_score: 82,
    trending_reason: 'Food content highest save rate of any niche',
    similar_views_avg: 980000,
    is_active: true,
    expires_at: null,
    created_at: new Date().toISOString(),
  },
]

export const MOCK_PROFILE = {
  id: 'mock-user-id',
  username: 'creator_dev',
  full_name: 'Your Name',
  avatar_url: null,
  niche: 'finance' as const,
  sub_niche: 'personal savings',
  platforms: ['instagram', 'youtube'] as const,
  content_formats: ['reel', 'short'] as const,
  monetisation_goal: {
    platform: 'instagram' as const,
    target_followers: 10000,
    current_followers: 6400,
  },
  plan: 'free' as const,
  stripe_customer_id: null,
  onboarding_completed: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}
