import type { Idea } from '@/types'

export const MOCK_IDEAS: Idea[] = [
  // ── LIFESTYLE ──────────────────────────────────────────────
  {
    id: 'ls-1', source: 'trending', created_by: null,
    title: 'Morning routine that actually changed my productivity',
    description: 'A realistic 45-min morning routine with science behind each habit. No 4am wakeups, no ice baths, no hustle porn.',
    hook_preview: '"I\'m not a morning person. This routine works even if you sleep until 8am..."',
    niche: 'lifestyle', sub_niche: 'productivity',
    platforms: ['tiktok'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 25, viral_score: 79,
    trending_reason: 'Productivity consistently top-5 saves category',
    similar_views_avg: 420000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ls-2', source: 'trending', created_by: null,
    title: 'I deleted social media for 30 days — what actually happened',
    description: 'Honest diary-style breakdown of anxiety, boredom, then clarity. Includes screen time stats before and after.',
    hook_preview: '"Day 1 I checked my phone 47 times out of muscle memory. By day 30, everything changed..."',
    niche: 'lifestyle', sub_niche: 'digital wellness',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'easy', estimated_minutes: 60, viral_score: 88,
    trending_reason: 'Digital detox content up 220% this quarter',
    similar_views_avg: 1100000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ls-3', source: 'trending', created_by: null,
    title: 'How I redesigned my tiny apartment for under ₹8,000',
    description: 'Budget room makeover using IKEA hacks, second-hand finds, and one key lighting trick that transforms any space.',
    hook_preview: '"₹8,000 and one weekend. My landlord thought I renovated..."',
    niche: 'lifestyle', sub_niche: 'home decor',
    platforms: ['youtube'], recommended_format: 'reel',
    difficulty: 'medium', estimated_minutes: 40, viral_score: 85,
    trending_reason: 'Budget home decor up 180% saves this month',
    similar_views_avg: 760000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ls-4', source: 'trending', created_by: null,
    title: 'The reading habit that changed how I think',
    description: 'A system for reading 24 books a year without sacrificing sleep or hustle culture. Works for busy people.',
    hook_preview: '"I used to say I had no time to read. Then I found 45 minutes hiding in plain sight..."',
    niche: 'lifestyle', sub_niche: 'reading habits',
    platforms: ['tiktok'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 20, viral_score: 76,
    trending_reason: 'BookTok trend in full swing across demographics',
    similar_views_avg: 320000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ls-5', source: 'trending', created_by: null,
    title: 'My honest 6-month minimalism experiment',
    description: 'What I kept, what I threw away, and the surprising way owning less made me richer — mentally and financially.',
    hook_preview: '"I owned 312 things I forgot existed. Selling them changed my relationship with money..."',
    niche: 'lifestyle', sub_niche: 'minimalism',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'medium', estimated_minutes: 75, viral_score: 81,
    trending_reason: 'Minimalism content rebounding after pandemic buying era',
    similar_views_avg: 540000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ls-6', source: 'trending', created_by: null,
    title: 'Journaling changed my anxiety — here\'s my exact method',
    description: 'A 10-minute evening journaling ritual backed by CBT principles. Reduces overthinking, builds clarity.',
    hook_preview: '"My therapist gave me this exercise. I\'ve done it 180 days straight. This is what happened..."',
    niche: 'lifestyle', sub_niche: 'mental health',
    platforms: ['tiktok', 'youtube'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 20, viral_score: 92,
    trending_reason: 'Mental health content drives highest share rates this year',
    similar_views_avg: 1800000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  // ── FINANCE ──────────────────────────────────────────────
  {
    id: 'fi-1', source: 'trending', created_by: null,
    title: 'How I saved ₹50,000 in 6 months on a ₹30k salary',
    description: 'Personal finance breakdown showing exact budget splits, zero-based budgeting, and small wins that compound.',
    hook_preview: '"Everyone says save money. Nobody shows HOW on a low salary. Here\'s my exact breakdown..."',
    niche: 'finance', sub_niche: 'personal savings',
    platforms: ['youtube'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 30, viral_score: 91,
    trending_reason: '4.2M views on similar content this week',
    similar_views_avg: 890000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'fi-2', source: 'trending', created_by: null,
    title: 'Index funds explained in 5 minutes — even my parents understood',
    description: 'No jargon. Pure visual explainer on how index funds work, why they outperform most mutual funds, and how to start.',
    hook_preview: '"My dad has been selling ₹3,000 FDs every year. I showed him this. He cried..."',
    niche: 'finance', sub_niche: 'investing',
    platforms: ['youtube'], recommended_format: 'short',
    difficulty: 'easy', estimated_minutes: 35, viral_score: 87,
    trending_reason: 'Index fund searches up 410% after SEBI campaign',
    similar_views_avg: 720000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'fi-3', source: 'trending', created_by: null,
    title: 'The credit card mistake 90% of Indians make every month',
    description: 'The minimum payment trap explained with real math. Shows how ₹10,000 debt becomes ₹24,000 in 2 years.',
    hook_preview: '"Banks make ₹4,000 from you every month and you thank them for the rewards..."',
    niche: 'finance', sub_niche: 'debt management',
    platforms: ['youtube'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 20, viral_score: 94,
    trending_reason: 'Credit card debt content surging post-festival season',
    similar_views_avg: 2100000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'fi-4', source: 'trending', created_by: null,
    title: 'I invested ₹500/month for 10 years — here\'s the reality',
    description: 'Long-term SIP breakdown using actual NIFTY50 data. Shows the power of consistency with real portfolio screenshots.',
    hook_preview: '"₹500 a month sounded pointless. The calculator proved me embarrassingly wrong..."',
    niche: 'finance', sub_niche: 'SIP investing',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'medium', estimated_minutes: 65, viral_score: 83,
    trending_reason: 'SIP education at all-time high after mutual fund awareness push',
    similar_views_avg: 560000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  // ── TECH ──────────────────────────────────────────────────
  {
    id: 'tc-1', source: 'trending', created_by: null,
    title: '5 AI tools replacing expensive freelancers in 2025',
    description: 'Practical demo of 5 tools that automate design, writing, video editing, and customer support. Cost comparison included.',
    hook_preview: '"I paid someone ₹20,000 a month for this. Now I use these 5 free tools instead..."',
    niche: 'tech', sub_niche: 'AI tools',
    platforms: ['youtube'], recommended_format: 'short',
    difficulty: 'medium', estimated_minutes: 45, viral_score: 87,
    trending_reason: 'AI tools niche up 340% search volume',
    similar_views_avg: 650000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'tc-2', source: 'trending', created_by: null,
    title: 'I built a SaaS in 48 hours using AI — full honest breakdown',
    description: 'Speed-run of building a real product with Claude, Cursor, and Supabase. What worked, what broke, revenue on launch day.',
    hook_preview: '"48 hours. No team. No designer. ₹12,000 MRR by Monday..."',
    niche: 'tech', sub_niche: 'indie hacking',
    platforms: ['youtube', 'twitter'], recommended_format: 'long_form',
    difficulty: 'hard', estimated_minutes: 90, viral_score: 89,
    trending_reason: 'Vibe coding and AI development content hitting mainstream',
    similar_views_avg: 830000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'tc-3', source: 'trending', created_by: null,
    title: 'ChatGPT prompts that actually save me 3 hours a day',
    description: 'Real workflow integration: writing, research, coding, email drafts. Prompt templates included in description.',
    hook_preview: '"ChatGPT is boring until you stop treating it like Google..."',
    niche: 'tech', sub_niche: 'productivity tools',
    platforms: ['youtube', 'tiktok'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 30, viral_score: 93,
    trending_reason: 'Productivity + AI crossover is the hottest category right now',
    similar_views_avg: 2400000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'tc-4', source: 'trending', created_by: null,
    title: 'The app that\'s secretly draining your phone battery',
    description: 'Hidden background processes exposed. Includes which apps to delete and what to replace them with for better battery life.',
    hook_preview: '"This one app used 34% of your battery while you slept. Most people don\'t know it\'s there..."',
    niche: 'tech', sub_niche: 'smartphones',
    platforms: ['tiktok'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 15, viral_score: 86,
    trending_reason: 'Phone tips get 4x usual share rate across demographics',
    similar_views_avg: 1200000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  // ── FITNESS ───────────────────────────────────────────────
  {
    id: 'ft-1', source: 'trending', created_by: null,
    title: 'Gym workout for people who hate the gym',
    description: 'Minimal equipment, 30-min sessions, real body transformation. Anti-gym-bro energy. Relatable and achievable.',
    hook_preview: '"Been going to the gym for 2 years with zero results. Then I changed one thing..."',
    niche: 'fitness', sub_niche: 'beginner fitness',
    platforms: ['youtube', 'tiktok'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 35, viral_score: 88,
    trending_reason: '2.1M saves on anti-bro fitness content this month',
    similar_views_avg: 750000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ft-2', source: 'trending', created_by: null,
    title: 'I walked 10,000 steps a day for 90 days — the honest results',
    description: 'Body composition, mood, sleep quality, and weight data tracked across 90 days with zero diet changes.',
    hook_preview: '"No gym. No diet. Just walking. The blood test result shocked my doctor..."',
    niche: 'fitness', sub_niche: 'walking fitness',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'easy', estimated_minutes: 50, viral_score: 91,
    trending_reason: 'Low-effort fitness content outperforms intense workout content 3:1',
    similar_views_avg: 1600000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ft-3', source: 'trending', created_by: null,
    title: 'Home workout that built real muscle — no equipment needed',
    description: 'Progressive overload principles applied to bodyweight training. 12-week program with visible results.',
    hook_preview: '"I was embarrassed to start. 90 days later I cancelled my gym membership..."',
    niche: 'fitness', sub_niche: 'home workout',
    platforms: ['youtube'], recommended_format: 'reel',
    difficulty: 'medium', estimated_minutes: 40, viral_score: 83,
    trending_reason: 'Home workout content has permanently expanded audience post-COVID',
    similar_views_avg: 620000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ft-4', source: 'trending', created_by: null,
    title: 'What eating high-protein for 30 days actually feels like',
    description: 'Real food diary, grocery costs, energy levels, and body changes from eating 150g protein/day for a month.',
    hook_preview: '"Day 1 I felt like a bodybuilder. Day 7 I was exhausted and bloated. Here\'s what really happens..."',
    niche: 'fitness', sub_niche: 'nutrition',
    platforms: ['tiktok', 'youtube'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 30, viral_score: 86,
    trending_reason: 'High protein trend at peak engagement across all platforms',
    similar_views_avg: 940000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  // ── FOOD ──────────────────────────────────────────────────
  {
    id: 'fd-1', source: 'trending', created_by: null,
    title: 'Restaurant-quality biryani — the step everyone skips',
    description: 'Step-by-step recipe exposing the one technique that separates home cooks from restaurant quality.',
    hook_preview: '"Every biryani recipe lies to you about one step. Here\'s what they all skip..."',
    niche: 'food', sub_niche: 'Indian cooking',
    platforms: ['youtube'], recommended_format: 'reel',
    difficulty: 'medium', estimated_minutes: 40, viral_score: 82,
    trending_reason: 'Food content highest save rate of any niche',
    similar_views_avg: 980000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'fd-2', source: 'trending', created_by: null,
    title: 'Meal prep for the whole week under ₹1,500',
    description: 'Sunday batch cooking that gives you 21 meals for the week. Calorie-counted, high-protein, actually tasty.',
    hook_preview: '"I was spending ₹6,000 a month on Zomato. This one habit ended that..."',
    niche: 'food', sub_niche: 'meal prep',
    platforms: ['youtube', 'tiktok'], recommended_format: 'reel',
    difficulty: 'medium', estimated_minutes: 45, viral_score: 90,
    trending_reason: 'Budget meal prep exploding across all urban demographics',
    similar_views_avg: 1400000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'fd-3', source: 'trending', created_by: null,
    title: 'Viral street food I tried in 5 Indian cities — ranked',
    description: 'Honest review format documenting regional street food gems across Mumbai, Delhi, Kolkata, Chennai, Pune.',
    hook_preview: '"I spent ₹800 in total eating across 5 cities. The ranking will surprise every Indian..."',
    niche: 'food', sub_niche: 'street food',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'medium', estimated_minutes: 80, viral_score: 85,
    trending_reason: 'Regional food tourism at all-time content high post-pandemic',
    similar_views_avg: 870000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'fd-4', source: 'trending', created_by: null,
    title: 'I only ate protein for 7 days — every meal documented',
    description: 'Extremely high-protein food challenge with taste ratings, cost, and what it actually did to energy and body.',
    hook_preview: '"7 days. 150g protein/day. I didn\'t expect to feel this way by day 4..."',
    niche: 'food', sub_niche: 'food challenges',
    platforms: ['tiktok'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 25, viral_score: 88,
    trending_reason: 'Protein food challenge getting massive organic reach',
    similar_views_avg: 1100000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  // ── EDUCATION ─────────────────────────────────────────────
  {
    id: 'ed-1', source: 'trending', created_by: null,
    title: 'What no one tells you about starting a YouTube channel',
    description: 'The real numbers: views, revenue, time invested vs returns. Myth-busting format showing month-by-month data.',
    hook_preview: '"I made ₹0 for 8 months. Here\'s what actually changes everything in month 9..."',
    niche: 'education', sub_niche: 'creator economy',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'medium', estimated_minutes: 90, viral_score: 84,
    trending_reason: 'Creator economy content surging after YT update',
    similar_views_avg: 1200000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ed-2', source: 'trending', created_by: null,
    title: 'I studied with Feynman technique for 30 days — here\'s what changed',
    description: 'Applying the Nobel Prize physicist\'s learning method to exam prep. Specific subject breakdown with before/after test scores.',
    hook_preview: '"I failed my exam 3 times. Then I stopped highlighting and started doing this instead..."',
    niche: 'education', sub_niche: 'study techniques',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'easy', estimated_minutes: 70, viral_score: 82,
    trending_reason: 'Study method content performing best among 16-24 demographic',
    similar_views_avg: 680000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'ed-3', source: 'trending', created_by: null,
    title: 'How I learned to code in 6 months with zero CS degree',
    description: 'The exact free resources, daily schedule, and first freelance job landing. Specifically targeted at Indian job market.',
    hook_preview: '"₹0 spent on courses. ₹50,000 first freelance invoice. The path nobody talks about..."',
    niche: 'education', sub_niche: 'self-learning',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'medium', estimated_minutes: 85, viral_score: 90,
    trending_reason: 'Self-taught developer stories getting 5M+ views routinely',
    similar_views_avg: 1500000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  // ── TRAVEL ─────────────────────────────────────────────────
  {
    id: 'tr-1', source: 'trending', created_by: null,
    title: 'Goa for ₹8,000 all-inclusive — the insider budget guide',
    description: 'Real cost breakdown for 4 days: transport, stay, food, activities. Avoiding tourist traps with actual alternatives.',
    hook_preview: '"Everyone told me Goa was expensive. I did it for ₹2,000 a day including everything..."',
    niche: 'travel', sub_niche: 'budget travel',
    platforms: ['youtube'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 35, viral_score: 86,
    trending_reason: 'Budget India travel content surging with domestic tourism',
    similar_views_avg: 760000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  {
    id: 'tr-2', source: 'trending', created_by: null,
    title: 'I solo traveled Southeast Asia for ₹80,000 — full breakdown',
    description: '3-country, 21-day trip covering Thailand, Vietnam, Bali. Visa fees, accommodation, transportation, honest opinions.',
    hook_preview: '"₹80,000 for 21 days across 3 countries including flights. Here\'s every rupee spent..."',
    niche: 'travel', sub_niche: 'backpacking',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'medium', estimated_minutes: 95, viral_score: 88,
    trending_reason: 'Southeast Asia budget travel content massive organic reach',
    similar_views_avg: 1300000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  // ── GAMING ─────────────────────────────────────────────────
  {
    id: 'gm-1', source: 'trending', created_by: null,
    title: 'How I made my first ₹10,000 streaming on YouTube Gaming',
    description: 'From 0 viewers to monetisation. Real timeline, game choices that worked, thumbnail A/B tests, and first sponsorship story.',
    hook_preview: '"Month 1: 0 views. Month 6: ₹10,000 cheque. This is the exact path nobody explains..."',
    niche: 'gaming', sub_niche: 'streaming tips',
    platforms: ['youtube'], recommended_format: 'long_form',
    difficulty: 'medium', estimated_minutes: 70, viral_score: 80,
    trending_reason: 'Gaming creator content for aspiring streamers growing 2x YoY',
    similar_views_avg: 480000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
  // ── BEAUTY ─────────────────────────────────────────────────
  {
    id: 'be-1', source: 'trending', created_by: null,
    title: 'Skincare routine for under ₹500/month that actually works',
    description: 'Minimalist 3-step routine using accessible Indian drugstore products. Before/after with 90-day tracking.',
    hook_preview: '"₹6,000 on serums vs ₹500 on this. My dermatologist couldn\'t tell the difference..."',
    niche: 'beauty', sub_niche: 'skincare',
    platforms: ['youtube', 'tiktok'], recommended_format: 'reel',
    difficulty: 'easy', estimated_minutes: 25, viral_score: 89,
    trending_reason: 'Budget skincare content outperforming luxury reviews 4:1',
    similar_views_avg: 1200000, is_active: true, expires_at: null, created_at: new Date().toISOString(),
  },
]


export const MOCK_PROFILE = {
  id: 'mock-user-id',
  username: 'creator_dev',
  full_name: 'Your Name',
  avatar_url: null,
  niche: 'finance' as const,
  sub_niche: 'personal savings',
  platforms: ['youtube'] as const,
  content_formats: ['reel', 'short'] as const,
  monetisation_goal: {
    platform: 'youtube' as const,
    target_followers: 10000,
    current_followers: 6400,
  },
  plan: 'free' as const,
  stripe_customer_id: null,
  onboarding_completed: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}
